### ISSUE TITLE
Link to GitHub issue incorrectly parsed as a tag

### ISSUE THREAD

**Issue by ngirard** [datopian/markdowndb#100]
Using latest mddb on Ubuntu 23.04.

One of my notes contains
<pre>
Doctests now include rustc-link-args from build scripts. [#9916](https://github.com/rust-lang/cargo/pull/9916)
</pre>

and caused mddb to try and insert '9916' as a tag.

**Comment by mohamedsalem401** [comment]
FIXED. Tags in Obsidian should have at least 1 alphabetical character to be considered a valid tag. See [Obsidian documentation on Editing and formatting Tags](https://help.obsidian.md/Editing+and+formatting/Tags).

Now, markdownDB ignores such tags as well. (Luckily for you, this should fix the case where GitHub issue numbers are being unnecessarily extracted.)

**Comment by ngirard** [comment]
Great, thanks @mohamedsalem401 !
