### ISSUE TITLE
Escaped hashes incorrectly parsed as a tag

### ISSUE THREAD

**Issue by ngirard** [datopian/markdowndb#105]
Using latest MarkdownDB version on Ubuntu 23.04 via `npx mddb@latest --watch ~/Obsidian`.

One of my note contains
```
The original home of \#100SecondsOfCode and \#CodeThisNotThat.
```
(this is an excerpted description of a Youtube video)
and caused mddb to try and insert `100SecondsOfCode` and `CodeThisNotThat` as tags.

**Comment by mohamedsalem401** [comment]
@ngirard This is caused by remark-parse (a library that converts markdown files to AST) ignoring `\`, so MarkdownDB can't know that this is escaped. This will need some time to fix.

**Comment by rufuspollock** [comment]
WONTFIX. I don't think we'll fix this for now as it is a pretty rare edge case. I think the best would be to fix in source by using e.g. backticks to mark these as code in the rare cases these happen.
