### ISSUE TITLE
Hashtag in link name incorrectly parsed as a tag

### ISSUE THREAD

**Issue by ngirard** [datopian/markdowndb#107]
Using latest MarkdownDB version on Ubuntu 23.04 via npx mddb@latest --watch ~/Obsidian.

One of my notes contains

```md
... with [#Gentoo](https://gentoo.org) and [#ArchLinux](https://archlinux.org), ...
```
(this is an excerpted description of a GitHub account)
and caused mddb to try and insert `Gentoo` and `ArchLinux` as tags.

This looks similar to #100.

**Comment by mohamedsalem401** [comment]
@ngirard This is expected behavior, as Obsidian considers those to be tags, and so should we (some users might want to include tags in a link name 🙂)

**Comment by mohamedsalem401** [comment]
WONTFIX. This is an expected and wanted behavior
