### ISSUE TITLE
Add instructions for developers to README

### ISSUE THREAD

**Issue by olayway** [datopian/markdowndb#13]
E.g. how to version, tag and publish

**Comment by AdamQuadmon** [comment]
Nice project!
I'd like to contribute.
Switching from contentLayer I'm currently using mddb to generate the sqlite db but having issues with the sqlClient I'm just using a pure sqlite connector to get data.

I'm working on a NextJs13 app router project using PandaCSS for styling.
Right now I'm implementing some decorators to compute fields and set defaults.

Let me know if there is something I can do in this direction and if there is a discord for this.

**Comment by rufuspollock** [comment]
@AdamQuadmon just saw your message on this thread - sorry we missed it earlier. Here's the discord channel - https://discord.gg/EeyfGrGu4U

**Comment by rufuspollock** [comment]
WONTFIX. We'll reopen when we have a need - please ping if you want to contribute!
