### ISSUE TITLE
Announce our MarkdownDB tutorial

### ISSUE THREAD

**Issue by olayway** [datopian/markdowndb#17]
## Acceptance
- [x]  Twitter
  - [x] draft a tweet
  - [x] tweet
- [ ] ...

**Comment by olayway** [comment]
@rufuspollock The tutorial is ready. Do we want to post it somewhere? Or just post a tweet and add a link to the README with tutorial in the example app?

**Comment by rufuspollock** [comment]
@olayway yes ... and first simplest thing (<20m) is a tweet from datopian twitter about it linking to project and the tutorial.

So first step: draft the tweet and post it here. Bonus (adds 5-10m) would be a screenshot or short gif showing it in action (can make a gif out of multiple screenshots strung together with a pause between them ...)

PS: can you link the tutorial in this issue (so i can take a look).

**Comment by olayway** [comment]
@rufuspollock, @ZybN

Here is my first attempt:

---

🚀 Ready to put #MarkdownDB into action? Great! We've just created a basic tutorial for you!

👉 Check it out: https://github.com/datopian/markdowndb/blob/main/examples/basic-example/README.md

🧵👇

<<< GIF OF MDDB IN ACTION HERE >>>

**1/5** 🗂️ Step1 : Prepare a folder with your markdown files.

**2/5** 🗃️ Step 2: Index it with `npx @flowershow/markdowndb <your-content>`

**3/5** 🔍 Step 3: Explore the SQLite database with any SQLite viewer or in command line.

**4/5** 🤖 Step 4: Install MarkdownDB package in your Node.js app and query your markdown files! More info on this step in the tutorial up above 👆

**5/5** 🙏 Step 5: Give us feedback so that we can make this tool better for you!

---

Let me know what you think :)

**Comment by rufuspollock** [comment]
Really good - this can come a few days after we do first announce tweets

**Comment by olayway** [comment]
Published https://twitter.com/datopian/status/1661012395324739586
