### ISSUE TITLE
Announce MarkdownDB on Twitter

### ISSUE THREAD

**Issue by olayway** [datopian/markdowndb#18]
## Acceptance
- [ ] draft tweets thread
- [ ] publish

**Comment by rufuspollock** [comment]
@olayway looks good - ship early, ship often. Let's get this announce out asap 😄

**Comment by olayway** [comment]
@rufuspollock  do we want to invite people to Discord? If so, which one? See last tweet in the thread.

**Comment by olayway** [comment]
@rufuspollock nvmd, I think I'll just say `star` us on GH or sth and if we ever create a discord channel we can tweet about it too ;)

**Comment by olayway** [comment]
Done https://twitter.com/datopian/status/1658818662600523782
