### ISSUE TITLE
Tutorial: "How to create a data catalog out of markdown files using free tools?"

### ISSUE THREAD

**Issue by olayway** [datopian/markdowndb#20]
## Acceptance
- [ ] write a tutorial with the following content structure

<img width="1359" alt="image" src="https://github.com/datopian/markdowndb/assets/52197250/899958d2-fd9f-4512-bbad-bde5ceec2d22">

**Comment by rufuspollock** [comment]
FIXED. see https://github.com/datopian/markdowndb/tree/main/examples/obsidian-dataview
