### ISSUE TITLE
MarkdownDB fails with more than 500 files in a top directory

### ISSUE THREAD

**Issue by luccasmmg** [datopian/markdowndb#22]
## Steps to reproduce

- Copy a directory with more than 500 markdown files inside to your `content` folder eg: https://github.com/openspending/community.openspending.org/tree/gh-pages/resources

Try indexing this in markdowndb, this is the outcome
![image](https://github.com/datopian/markdowndb/assets/11317382/df67c5ce-a9ba-4b41-95ae-21fb0fde0a49)

I've also tried indexing this directory on a fresh flowershow app, following this guide https://flowershow.app/docs/publish-tutorial and on the export section it will silently fail, but it will build again if i remove that dir

## Possible problem

I'm pretty sure the problem lies somewhere here, from what i could gather in [stackoverflow](https://stackoverflow.com/questions/9527851/sqlite-error-too-many-terms-in-compound-select), sqlite has a limit on the batch insert of 500, so a possible fix would be to slice the `filesToInsert` variable in batches of 499 and then insert each batch separatedly.
https://github.com/datopian/markdowndb/blob/main/src/lib/markdowndb.ts#LL181C4-L181C4

**Comment by rufuspollock** [comment]
@luccasmmg do you think you could look at doing this patch?

**Comment by olayway** [comment]
@luccasmmg that's a good catch! This definitely needs to be solved for the first indexing run but this reminded me that we could also probably use some way to not re-index the whole content folder each time the server is restarted, although I'm not yet sure how this could be done. Anyway, I'll take care of it. Thanks for the proposed solution!

**Comment by rufuspollock** [comment]
@olayway this is probably pretty urgent as it will break all flowershow sites over 500 files right ...?

**Comment by dstengle** [comment]
It looks like this fix got lost somewhere along the way. Possible to bring it back? I can't quite figure out where it went.

**Comment by dstengle** [comment]
Found it: https://github.com/datopian/markdowndb/commit/f6fe5b0899700462360e864c231473be99df91b0

Looks like things got moved around here and now there is both duplicate and missing code?

**Comment by rufuspollock** [comment]
@mohamedsalem401 can you look at this asap ... is this now broken or is it fixed.

**Comment by mohamedsalem401** [comment]
@dstengle @rufuspollock 
You are right, the fix needs to be re-added.

**Comment by mohamedsalem401** [comment]
This is fixed
