### ISSUE TITLE
Pages not generated for files with specific names in content folder

### ISSUE THREAD

**Issue by khalilcodes** [datopian/markdowndb#25]
Adding a markdown file or page in the content directory starting with the word "obsidian" does not generate a path in markdown.db thus rendering a 404 page.

## Acceptance

- [x] pages with word "obsidian" generate and render

## Tasks

- [x] fix regex for ignore path patterns
- [ ] ...

## Notes:

The ignore regex pattern in `scripts/mddb` may be the underlying issue - 

`const ignorePatterns = [/Excalidraw/, /.obsidian/, /DS_Store/];`

**Comment by olayway** [comment]
Fixed with 04a776f
