### ISSUE TITLE
Test for 500+ files

### ISSUE THREAD

**Issue by olayway** [datopian/markdowndb#26]
Aside: Probably in future we want a test of some kind - for now we could just open an issue about adding a test so we don't forget.

_Originally posted by @rufuspollock in https://github.com/datopian/markdowndb/issues/24#issuecomment-1579178901_

**Comment by rufuspollock** [comment]
WONTFIX. At least for now. (not a priority atm)

**Comment by dstengle** [comment]
I think you need this due to the regression that has happened. I could have a go at writing it.
