### ISSUE TITLE
Config file with basic content include/exclude options

### ISSUE THREAD

**Issue by olayway** [datopian/markdowndb#40]
## Acceptance **✅19-12-2023** #97 

A config file that allows for setting:
- [x] path to content directory (defaults to `./content`)
- [x] files/directories to include
- [x] files/directories to exclude
- [x] 🏆 `npx markdowndb init` CLI script that will bootstrap the config file ( This is not needed )

**Comment by rufuspollock** [comment]
@mohamedsalem401 is this done?
