### ISSUE TITLE
Could not find a declaration file for module 'mddb'

### ISSUE THREAD

**Issue by AdamQuadmon** [datopian/markdowndb#43]
I'm having this TypeScript issue using the client on a NextJs app with type: module set in package.json

```ts
// @ts-expect-error Could not find a declaration file for module 'mddb'
import { MarkdownDB } from "mddb";
```

**Comment by rufuspollock** [comment]
@olayway do we have the typescript types set for MarkdownDB?

**Comment by rufuspollock** [comment]
@mohamedsalem401 can you take a look at this and see if you can fix.

**Comment by mohamedsalem401** [comment]
I think the issue has to do with the fact that the library doesn't generate type declaration (.d.ts) files. I believe changing the tsconfig file will fix this issue.

**Comment by rufuspollock** [comment]
Let's get a PR in with short description and then we'll merge to main and then v2.
