### ISSUE TITLE
Is there a program to update the database in real time for real time previews

### ISSUE THREAD

**Issue by Ahidada** [datopian/markdowndb#45]
We want a way so that you can rebuild the database in real time so that we get real time previews.

Simplest approach is probably to use https://github.com/paulmillr/chokidar to watch the markdown folders and rebuild some json files (with these files being watched by nextjs or whatever tool you are using). this at least is a first pass. 

This probably depends on the JSON output option.

## Acceptance

- [x] Instructions for how to run this in watch mode so that that the markdowndb files are regularly rebuilt

**Comment by rufuspollock** [comment]
@Ahidada we know exactly what you want - we need to add a watch function to rebuild. This is on our roadmap but is not there atm.

You could hack this right now by running the rebuild script with a watch function on your content folder.

**Comment by rufuspollock** [comment]
@mohamedsalem401 could you put some info about how this was resolved and where it is documented ...

**Comment by mohamedsalem401** [comment]
Fixed here: [https://github.com/datopian/markdowndb/pull/90](https://github.com/datopian/markdowndb/pull/90)
Basically, by using the `--watch` flag on the command line (`mddb ./content --watch`). And no, we didn't add a documentation page back then.

**Comment by rufuspollock** [comment]
@mohamedsalem401 can we add something to README briefly about this functionality.

**Comment by mohamedsalem401** [comment]
@rufuspollock 
Here's the section in `Readme.md` about the watch flag
https://github.com/datopian/markdowndb?tab=readme-ov-file#watching-for-changes
