### ISSUE TITLE
Tags extraction from body

### ISSUE THREAD

**Issue by olayway** [datopian/markdowndb#49]
Currently, only frontmatter tags are being extracted.

## Acceptance

- [x] tags are also extracted from the markdown body ✅2023-11-17 ( see [PR](https://github.com/datopian/markdowndb/pull/57) )
- [x] tests ✅2023-11-17 ( see [PR](https://github.com/datopian/markdowndb/pull/57) )

**Comment by mohamedsalem401** [comment]
This is merged into `v2` branch✅2023-11-17 ( see [PR](https://github.com/datopian/markdowndb/pull/57) )
