### ISSUE TITLE
Move all the tests into a root test folder

### ISSUE THREAD

**Issue by rufuspollock** [datopian/markdowndb#67]
Some further refactoring.

- [x] Move all tests to root `test` folder
- [x]  merge utils with lib folder!
  - [x] remove utils/index.ts (no need)
- [ ] merge `indexFolder.ts` into `process.ts`

**Comment by mohamedsalem401** [comment]
@rufuspollock 
This is done as well, I will push https://github.com/datopian/markdowndb/issues/60 first tho.

**Comment by mohamedsalem401** [comment]
This is done

https://github.com/datopian/markdowndb/commit/dfe0cb5284134a6829f60573a2f95de5357563b3
