### ISSUE TITLE
Feature List of MarkdownDB on website

### ISSUE THREAD

**Issue by rufuspollock** [datopian/markdowndb#69]
## Acceptance

- [x] README.md updated **https://github.com/datopian/markdowndb/pull/85**
- [x] features list added on the MarkdownDB website **🛑 do this first - and fast**
  - [x] probably one section for each significant feature - use code like we have in the tutorial for the image. Probably a layout a bit like https://tailwindui.com/components/marketing/sections/feature-sections#component-11e5dbce11b8c462441792503ea864fc
- [x] write a blog post about new features - pretty much copy and past with headings of the above
- [x] prepare a Tweet thread (e.g. in HackMD) announcing new features (link to the blog post) - the post in chunked form
- [x] ask @popovayoana to tweet

## Questions / blockers

- [x] apart from posting on markdowndb.com, do we post the blog post about MarkdownDB new features anywhere else? **we don't post at markdowndb.com at all, post on [datahub.io](https://github.com/datopian/datahub-next/tree/main) instead**

## Notes

- examples of some old threads on Datopian Twitter (inspiration for the Tweet thread about MarkdownDB new features)
  - https://twitter.com/datopian/status/1712755357368336797
  - https://twitter.com/datopian/status/1661012395324739586

### Why use mddb?

- **Tag Querying:**
  - Retrieve tags from all files using the library.

- **Backward/Forward Links:**
  - Establish backward and forward links for a file, enhancing file interconnectivity.

- **Custom Field Calculation:**
  - Automatically calculate custom fields based on the content of a file.

- **Schema Validation:**
  - Ensure that your files adhere to a predefined schema through built-in validation.

- **Comprehensive Feature Set:**
  - The library offers a range of features to enhance file management and organization.

- **Content to Data Transformation:**
  - Convert content into a format that is usable by your code.

#### Later Features:
- **Next.js Watch Integration:**
  - Next.js doesn't watch for md file changes...
  - Utilize the library's Hot-reloading for seamless file change detection in Next.js.

- **Task Extraction:**
  - Extract tasks directly from files for improved task management and organization.

- **Extensibility and Plugins:**
  - Extend the functionality of mddb through plugins, allowing you to tailor the library to meet evolving needs and incorporate additional features seamlessly.

- **Searching capabilities:**
  - Search though all of your files by a simple query.
  - Integrate a search functionality by leveraging mddb's out of the box search capabilities.

---

X Thread

# MarkdownDB Tweet thread

🚀 Announcing #MarkdownDB cool new features: export to JSON, task extraction, and computed fields!

🧵👇

---

(1/4) 📤 Export to JSON files 📤

MarkdownDB now supports seamless export to #JSON!
Check out the example output in JSON format! 🚀

![json](https://github.com/datopian/markdowndb/assets/67981832/d9feed0a-c61e-4007-a0e4-c4ee04bd16d9)

<Link to docs page?>

---

(2/4) 📋 Task extraction 📋

Streamline task management with MarkdownDB! Extract tasks using robust queries.

![tasks](https://github.com/datopian/markdowndb/assets/67981832/2f8c5079-254e-4aa0-a44e-ccdc603c5e43)

<Link to docs page?>

---

(3/4) 🤖 Computed fields 🤖

Enrich your Markdown with additional metadata computed on the fly using custom functions.

![computed fields](https://github.com/datopian/markdowndb/assets/67981832/905216f8-df48-491c-84a4-68d8225458f1)

<Link to docs page?>

---

(4/4) 🚀 Getting Started 🚀

Excited? Dive into our [documentation](https://markdowndb.com/docs) for detailed instructions on how to use the new fatures today!

**Comment by olayway** [comment]
@mohamedsalem401 I've listed updating the README, writing a blog post and preparing a Twitter thread as subtasks of this issue as they are all closely related
