### ISSUE TITLE
Publish to markdowndb on npm

### ISSUE THREAD

**Issue by rufuspollock** [datopian/markdowndb#9]
We are already publishing to `@flowershow/markdowndb` ... and would like to publish to `markdowndb`. However, `markdown-db` is in use ...

## Tasks

- [x] Ping current owner of markdown-db to see if there is a way we can use `markdowndb` **✅2023-05-02 pinged him**
- [ ] See what happens

**Comment by olayway** [comment]
@rufuspollock For now I've used the original `@flowershow/markdown` name to publish the package. Until we have this sorted out.

**Comment by rufuspollock** [comment]
@olayway yes, this is blocked for now so use old name.

**Comment by olayway** [comment]
@rufuspollock have you heard from the markdowndb owner?

**Comment by rufuspollock** [comment]
@olayway no, so for now we keep our npm package name.

**Comment by olayway** [comment]
Do we wait or maybe go with `@datopian/markdowndb` or just `mddb`? 🙂

**Comment by rufuspollock** [comment]
@olayway `markdowndb` now seems available! https://www.npmjs.com/package/markdowndb 404s ... so we can use that 🎉

**Comment by rufuspollock** [comment]
WONTFIX. No response from owner and so let's leave for now and use `mddb`
