### ISSUE TITLE
Please add "db", "sql" and "database" to about.

### ISSUE THREAD

**Issue by dstengle** [datopian/markdowndb#94]
I was so excited to find this 2 days ago and forgot to star it and had more trouble than I should have finding it again. github search is terrible and these keywords would likely help this project get more visibility.

**Comment by rufuspollock** [comment]
@dstengle 👍

**Comment by rufuspollock** [comment]
FIXED. Added db and sql to keywords and tweaked README.

**Comment by dstengle** [comment]
Thank you!
